# Generated by Django 4.0.5 on 2022-08-25 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=150)),
                ('no_of_sem', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('sub_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=200)),
                ('sem', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('entrl_no', models.IntegerField(primary_key=True, serialize=False)),
                ('stud_name', models.CharField(max_length=200)),
                ('sem', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Marktable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub1', models.CharField(max_length=200, null=True)),
                ('sub2', models.CharField(max_length=200, null=True)),
                ('sub3', models.CharField(max_length=200, null=True)),
                ('sub4', models.CharField(max_length=200, null=True)),
                ('sem', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.course')),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.student')),
            ],
        ),
    ]
